name    'winbind'
version '0.0.1'
source 'https://github.com/fiddyspence/fiddyspence-winbind'
author 'fiddyspence'
license 'Apache License, Version 2.0'
summary 'manages samba winbind'
description 'join a windows domain using samba winbind'
